import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid,PieChart,Pie,Cell} from 'recharts';
import {Stats} from '../services/api';
export const colors=['#3b91f0','#25c69b','#f5b546','#a88cf1','#ed7794','#50c9dd'];
export function AnalyticsCharts({stats}:{stats:Stats}){
 const data=Object.entries(stats.classes).map(([name,value])=>({name,value}));
 return <div className="charts"><section className="card chart-card"><div className="card-title">Object count over time <span className="muted">● Live occupancy</span></div>
 {stats.series.length?<ResponsiveContainer width="100%" height={190}><AreaChart data={stats.series}><defs><linearGradient id="blue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#378cf6" stopOpacity={.3}/><stop offset="100%" stopColor="#378cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="time" tickFormatter={v=>new Date(v*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} minTickGap={45} tick={{fill:'#8394ad',fontSize:10}}/><YAxis allowDecimals={false} width={28} tick={{fill:'#8394ad',fontSize:10}}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)',borderRadius:8}} labelFormatter={v=>new Date(Number(v)*1000).toLocaleTimeString()}/><Area name="Present" type="stepAfter" dataKey="current" stroke="#378cf6" fill="url(#blue)" isAnimationActive={false}/><Area name="Unique tracks" type="stepAfter" dataKey="unique" stroke="#25c69b" fill="transparent" isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<div className="chart-empty">Your session timeline will appear here.</div>}</section>
 <section className="card chart-card"><div className="card-title">Class distribution <span className="muted">Unique tracks</span></div><div className="donut-row">{data.length?<><div className="donut"><ResponsiveContainer width="100%" height={175}><PieChart><Pie data={data} dataKey="value" innerRadius={53} outerRadius={72} paddingAngle={3} stroke="none" isAnimationActive={false}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)'}}/></PieChart></ResponsiveContainer><div className="donut-center"><b>{stats.total_unique}</b><span>TRACKS</span></div></div><div className="legend">{data.map((d,i)=><div key={d.name}><i style={{background:colors[i%colors.length]}}/>{d.name}<b>{d.value}</b></div>)}</div></>:<div className="chart-empty">No objects counted yet.</div>}</div></section></div>
}
