import {useEffect,useState} from 'react';
import {Upload,Download,SlidersHorizontal,Check,RefreshCw} from 'lucide-react';
import {api,upload} from '../services/api';
export function Settings({settings,onSaved,run,busy,models,refresh}:{settings:any,onSaved:(s:any)=>void,run:(fn:()=>Promise<any>)=>void,busy:boolean,models:any,refresh:()=>Promise<void>}){
 const [draft,setDraft]=useState(settings),[cameras,setCameras]=useState<any[]>([]);
 useEffect(()=>setDraft(settings),[settings]);
 if(!draft)return <div className="card padded">Connecting to backend…</div>;
 const change=(k:string,v:unknown)=>setDraft({...draft,[k]:v});
 const preset=(v:string)=>setDraft({...draft,performance:v,image_size:v==='Quality'?640:v==='Performance'?320:416,inference_fps:v==='Quality'?10:v==='Performance'?5:8});
 const numbers=[['confidence','Confidence threshold',.1,.95,.05],['iou','NMS IoU threshold',.1,.95,.05],['inference_fps','Target inference FPS',1,30,1],['display_fps','Target display FPS',5,60,1],['frame_skip','Fixed frame skip (0 = auto)',0,30,1],['cpu_threads','CPU threads',1,16,1],['track_buffer','Lost-track buffer (inference steps)',5,120,1],['initial_inside','Initial occupancy for IN / OUT',0,1000000,1]];
 return <div className="settings-layout"><section className="card padded"><div className="card-title"><span><SlidersHorizontal size={18}/>Performance settings</span><span className="tag">CPU FIRST</span></div><p className="muted small">Stop analysis before saving performance settings. Changes apply to the next session.</p><label>Performance mode</label><div className="segmented">{['Quality','Balanced','Performance'].map(v=><button className={draft.performance===v?'selected':''} key={v} onClick={()=>preset(v)}>{v}</button>)}</div><div className="form-grid"><div><label>Inference resolution</label><select value={draft.image_size} onChange={e=>change('image_size',+e.target.value)}>{[320,416,480,640].map(v=><option key={v}>{v}</option>)}</select></div><div><label>Device</label><select value={draft.device} onChange={e=>change('device',e.target.value)}><option value="cpu">CPU</option><option value="cuda:0">CUDA GPU (optional)</option></select></div>{numbers.map(([k,label,min,max,step])=><div key={k}><label>{label}</label><input type="number" min={min} max={max} step={step} value={draft[k]} onChange={e=>change(String(k),+e.target.value)}/></div>)}<div><label>Bounded queue size</label><select value={draft.queue_size} onChange={e=>change('queue_size',+e.target.value)}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></div><div><label>Tracker</label><select value="bytetrack" disabled><option value="bytetrack">ByteTrack</option></select></div></div><label className="check"><input type="checkbox" checked={draft.adaptive} onChange={e=>change('adaptive',e.target.checked)}/>Adaptive CPU performance</label><p className="muted small">Adjustments occur at most every five seconds. RAM and frame queues stay bounded; detection metadata is stored on disk.</p><button className="primary" disabled={busy} onClick={()=>run(async()=>{const s=await api('/settings','PUT',draft);onSaved(s);await refresh()})}><Check size={16}/>Save settings</button></section>
 <div className="stack"><section className="card padded"><div className="card-title">Model manager <span className="tag">DYNAMIC CLASSES</span></div><p className="muted small">YOLO11 nano is the default pretrained model. Compatible custom detection checkpoints use their own class names.</p><label>Available model</label><select value={models?.active?.name||draft.model} onChange={e=>run(async()=>{await api('/models/load','POST',{name:e.target.value});await refresh()})}><option value={draft.model}>{draft.model}</option>{models?.available?.filter((m:any)=>m.name!==draft.model).map((m:any)=><option key={m.name} value={m.name}>{m.name}</option>)}</select><div className="model-state"><span className={'tiny-dot '+(!models?.active?.loaded?'gray':'')}/>{models?.active?.loaded?`${Object.keys(models.active.classes).length} classes loaded`:'Model not loaded'}</div><div className="row wrap gap"><button disabled={busy} onClick={()=>run(async()=>{await api('/models/pretrained','POST');await refresh()})}><Download size={15}/>Install YOLO11 nano</button><button disabled={busy} onClick={()=>run(async()=>{await api('/models/load','POST',{name:draft.model});await refresh()})}>Load selected</button><button disabled={busy} onClick={()=>run(async()=>{await api('/models/unload','POST');await refresh()})}>Unload</button></div><label className="upload-model"><Upload size={18}/><b>Upload custom .pt model</b><span>Up to 100 MB · standard Ultralytics detection models</span><input type="file" accept=".pt" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{await upload('/models/upload',file);await refresh()});e.target.value=''}}/></label><p className="muted small">Restricted checkpoint loading rejects unknown Python classes and executable pickle functions. Architectures needing custom Python code are unsupported.</p>{models?.active?.loaded&&<div className="class-chips">{Object.values(models.active.classes).map((name:any)=><span key={name}>{name}</span>)}</div>}</section><section className="card padded"><div className="card-title">Camera & appearance</div><div className="form-grid">{[['camera_index','Camera index'],['camera_width','Width'],['camera_height','Height'],['camera_fps','Camera FPS']].map(([k,label])=><div key={k}><label>{label}</label><input type="number" value={draft[k]} onChange={e=>change(k,+e.target.value)}/></div>)}<div><label>Theme</label><select value={draft.theme} onChange={e=>change('theme',e.target.value)}><option value="dark">Dark navy</option><option value="light">Light</option></select></div></div><button disabled={busy} onClick={()=>run(async()=>setCameras((await api('/camera')).cameras))}><RefreshCw size={14}/>Scan camera indices 0–3</button><p className="muted small">{cameras.length?cameras.map(c=>c.name).join(', '):'Camera access is provided by the local Python server.'}</p></section></div></div>
}
