import {useEffect,useRef,useState} from 'react';
import {Camera,Upload,Play,Pause,Square,Maximize,Disc,Download,Video,ScanLine,Image as ImageIcon,Volume2} from 'lucide-react';
import {api,Point,Stats,Zone} from '../services/api';
type Props={stats:Stats;busy:boolean;kind:string;camera:number;setCamera:(x:number)=>void;onStart:()=>void;onUpload:(kind:string)=>void;run:(f:()=>Promise<any>)=>void;videoUrl:string|null;line:Point[]|null;zones:Zone[];onGeometry:()=>void};
export function VideoViewer({stats,busy,kind,camera,setCamera,onStart,onUpload,run,videoUrl,line,zones,onGeometry}:Props){
 const stage=useRef<HTMLDivElement>(null),audio=useRef<HTMLAudioElement>(null);
 const [ratio,setRatio]=useState(16/9),[draw,setDraw]=useState<'line'|'zone'|null>(null),[points,setPoints]=useState<Point[]>([]),[zoneName,setZoneName]=useState('Zone A'),[volume,setVolume]=useState(0),[audioError,setAudioError]=useState(''),[seek,setSeek]=useState<number|null>(null),[original,setOriginal]=useState(false);
 const live=stats.status==='running',paused=stats.status==='paused',hasFrame=!!stats.session_id;
 useEffect(()=>{const a=audio.current;if(!a||!videoUrl)return;a.volume=volume;a.playbackRate=stats.speed||1;if(Math.abs(a.currentTime-stats.position)>.7)a.currentTime=stats.position;if(live&&volume>0)a.play().catch(()=>setAudioError('Click volume after playback starts to enable audio.'));else a.pause()},[stats.position,stats.speed,live,videoUrl,volume]);
 const saveLine=(p:Point[])=>run(async()=>{await api('/counting/line','POST',{points:p.map(([x,y])=>({x,y}))});setDraw(null);setPoints([]);onGeometry()});
 const click=(e:React.MouseEvent<SVGSVGElement>)=>{if(!draw)return;const r=e.currentTarget.getBoundingClientRect();const p:Point=[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];const next=[...points,p];if(next.length>20)return;setPoints(next);if(draw==='line'&&next.length===2)saveLine(next)};
 const saveZone=()=>run(async()=>{await api('/counting/zone','POST',{zones:[...zones,{name:zoneName,points}].map(z=>({...z,points:z.points.map(([x,y])=>({x,y}))}))});setDraw(null);setPoints([]);setZoneName(`Zone ${String.fromCharCode(66+zones.length)}`);onGeometry()});
 const control=(action:string,value=0)=>run(()=>api('/video/control','POST',{action,value}));
 return <section className="card viewer"><div className="viewer-top"><div className="source-title"><span className="source-icon">{kind==='image'?<ImageIcon size={18}/>:kind==='video'?<Video size={18}/>:<Camera size={18}/>}</span><div><b>{kind==='image'?'Image analysis':kind==='video'?'Video analysis':'Live detection'}</b><small>{stats.model||'Pretrained YOLO'} · CPU-first pipeline</small></div></div><div className="row gap"><span className={'status-label '+(live?'active':'')}>{live?'● LIVE':paused?'● PAUSED':stats.status.toUpperCase()}</span>{kind==='camera'&&<select aria-label="Camera selection" value={camera} onChange={e=>setCamera(Number(e.target.value))}>{Array.from({length:8},(_,i)=><option key={i} value={i}>Camera {i}</option>)}</select>}</div></div>
 <div ref={stage} className={'video-stage '+(draw?'drawing':'')} style={{aspectRatio:ratio,maxWidth:`calc(65vh * ${ratio})`}}>
 {hasFrame?<img alt="Detection output" src={stats.source_kind==='image'?(original?stats.original_url:stats.image_url):`/api/stream?session=${stats.session_id}`} onLoad={e=>{const img=e.currentTarget;if(img.naturalWidth)setRatio(img.naturalWidth/img.naturalHeight)}}/>:<div className="video-empty"><div className="scan-frame"><ScanLine size={46}/></div><span className="eyebrow">YOUR VISION WORKSPACE</span><h2>Every object. Accounted for.</h2><p>Connect a camera or add media to begin<br/>detection, tracking and live analytics.</p><div className="row gap"><button className="primary" disabled={busy} onClick={onStart}><Camera size={15}/>{kind==='image'?'Analyze image':kind==='video'?'Start video':'Start camera'}</button><button onClick={()=>onUpload('video')}><Upload size={15}/>Upload video</button></div><button className="text-button" onClick={()=>onUpload('image')}>Analyze an image <span>↗</span></button></div>}
 {(draw||!hasFrame)&&<svg className="drawing-layer" viewBox="0 0 1000 1000" preserveAspectRatio="none" onClick={click} style={{pointerEvents:draw?'auto':'none'}}>{zones.map(z=><polygon key={z.name} points={z.points.map(p=>`${p[0]*1000},${p[1]*1000}`).join(' ')} fill="#248ce522" stroke="#58a9ee" strokeWidth="2"/>)}{line&&<line x1={line[0][0]*1000} y1={line[0][1]*1000} x2={line[1][0]*1000} y2={line[1][1]*1000} stroke="#ffca64" strokeWidth="3"/>}<polyline points={points.map(p=>`${p[0]*1000},${p[1]*1000}`).join(' ')} fill={draw==='zone'?'#348ef522':'none'} stroke="#68b0ff" strokeWidth="3"/>{points.map((p,i)=><circle key={i} cx={p[0]*1000} cy={p[1]*1000} r="5" fill="#80c1ff"/>)}</svg>}
 {stats.recording&&<span className="recording-badge">● REC</span>}{draw&&<div className="draw-hint">{draw==='line'?'Click two endpoints. The positive side of the directed line is IN.':'Click polygon vertices, then save the zone.'}</div>}
 </div>
 {kind==='video'&&stats.duration>0&&<div className="timeline"><span>{formatTime(seek??stats.position)}</span><input aria-label="Video seek position" type="range" min="0" max={Math.max(0,stats.duration-.1)} step=".1" value={seek??Math.min(stats.position,stats.duration)} onChange={e=>setSeek(+e.target.value)} onPointerUp={()=>{if(seek!==null){control('seek',seek);setSeek(null)}}} onKeyUp={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)&&seek!==null){control('seek',seek);setSeek(null)}}}/><span>{formatTime(stats.duration)}</span></div>}
 <div className="viewer-controls"><div className="row gap"><button className="primary compact" disabled={busy} onClick={()=>live?control('pause'):paused?control('resume'):onStart()}>{live?<Pause size={16}/>:<Play size={16}/>} {live?'Pause':paused?'Resume':'Start'}</button><button title="Stop analysis" disabled={busy||(!live&&!paused)} onClick={()=>run(()=>api('/video/stop','POST'))}><Square size={15}/></button><span className="separator"/><button title="Save snapshot" disabled={!hasFrame} onClick={()=>run(async()=>{const d=await api('/snapshot','POST');download(d.url)})}><Camera size={16}/></button><button title="Toggle recording" className={stats.recording?'danger':''} disabled={!live&&!paused} onClick={()=>run(async()=>{const d=await api('/record','POST',{enabled:!stats.recording});if(d.url)download(d.url)})}><Disc size={16}/></button>{stats.source_kind==='image'&&<button onClick={()=>setOriginal(!original)}>{original?'Annotated':'Original'}</button>}</div><div className="row gap">{kind==='video'&&<><select aria-label="Playback speed" value={stats.speed||1} onChange={e=>control('speed',+e.target.value)}>{[.5,1,1.5,2].map(n=><option key={n} value={n}>{n}×</option>)}</select><Volume2 size={15}/><input className="volume" aria-label="Video audio volume" type="range" min="0" max="1" step=".1" value={volume} onChange={e=>{setVolume(+e.target.value);setAudioError('')}}/></>}<button title="Fullscreen" disabled={!!draw} onClick={()=>stage.current?.requestFullscreen().catch(()=>{})}><Maximize size={16}/></button></div></div>
 {kind==='video'&&<div className="playback-note">Seeking starts a fresh counting session. Audio depends on browser codec support.{audioError&&<span> {audioError}</span>}</div>}
 <div className="geometry-controls"><button className={draw==='line'?'selected':''} onClick={()=>{setDraw(draw==='line'?null:'line');setPoints([])}}><ScanLine size={14}/>Draw count line</button><button className={draw==='zone'?'selected':''} onClick={()=>{setDraw(draw==='zone'?null:'zone');setPoints([])}}>＋ Add zone</button>{draw==='zone'&&<><input aria-label="Zone name" value={zoneName} onChange={e=>setZoneName(e.target.value)} maxLength={40}/><button disabled={points.length<3} onClick={saveZone}>Save zone</button></>}{draw&&<button onClick={()=>{setDraw(null);setPoints([])}}>Cancel</button>}{line&&<button onClick={()=>run(async()=>{await api('/counting/line','DELETE');onGeometry()})}>Clear line</button>}{zones.length>0&&<button onClick={()=>run(async()=>{await api('/counting/zone','POST',{zones:[]});onGeometry()})}>Clear zones</button>}</div>
 {videoUrl&&<audio ref={audio} src={videoUrl} preload="metadata" onError={()=>setAudioError('This video’s audio codec is unsupported by your browser.')}/>}</section>
}
export function download(url:string){const a=document.createElement('a');a.href=url;a.download='';document.body.appendChild(a);a.click();a.remove()}
function formatTime(n:number){return `${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`}
