import {useEffect,useRef,useState} from 'react';
import {Eye,Camera,Image as ImageIcon,Video,ScanLine,BarChart3,History,Settings as SettingsIcon,Sun,Moon,User,ChevronRight,Download,Upload,CheckCircle2,AlertCircle,X,Cpu,HardDrive,ExternalLink,Box,ArrowDownLeft,ArrowUpRight,Layers,Activity} from 'lucide-react';
import {api,upload,Point,Zone} from './services/api';
import {useDetection} from './hooks/useDetection';
import {AnalyticsCharts} from './components/AnalyticsCharts';
import {ObjectCountPanel,StatsPanel,RecentDetections} from './components/Panels';
import {VideoViewer,download} from './components/VideoViewer';
import {Settings} from './components/Settings';
const pages=[['Live Detection',Camera],['Image Upload',ImageIcon],['Video Analysis',Video],['Counting Modes',ScanLine],['Analytics',BarChart3],['History',History],['Settings',SettingsIcon]] as const;
const modes=['Class-wise','Total count','Live occupancy','Line crossing','Zone counting','IN / OUT'];
export default function App(){
 const {stats,setStats,online}=useDetection();
 const [page,setPage]=useState('Live Detection'),[mode,setMode]=useState('Class-wise'),[kind,setKind]=useState('camera'),[camera,setCamera]=useState(0);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[settings,setSettings]=useState<any>(null),[models,setModels]=useState<any>(null),[sessions,setSessions]=useState<any[]>([]),[profile,setProfile]=useState(false);
 const [line,setLine]=useState<Point[]|null>(null),[zones,setZones]=useState<Zone[]>([]),[videoFile,setVideoFile]=useState<string|null>(null),[videoUrl,setVideoUrl]=useState<string|null>(null),[imageFile,setImageFile]=useState<File|null>(null),[job,setJob]=useState<any>({status:'idle'}),[showAllClasses,setShowAllClasses]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null),uploadKind=useRef('video');
 const refresh=async()=>{const [s,m,g]=await Promise.all([api('/settings'),api('/models'),api('/counting')]);setSettings(s);setModels(m);setLine(g.line);setZones(g.zones);setCamera(s.camera_index)};
 useEffect(()=>{refresh().catch(e=>{setMessage(e.message);setError(true)})},[online]);
 useEffect(()=>{document.documentElement.dataset.theme=settings?.theme||'dark'},[settings?.theme]);
 useEffect(()=>{if(page==='History')api('/history').then(setSessions).catch(()=>{})},[page,stats.status]);
 useEffect(()=>{if(job.status!=='running')return;const timer=setInterval(()=>api('/video/export').then(setJob).catch(()=>{}),1000);return()=>clearInterval(timer)},[job.status]);
 async function run(fn:()=>Promise<any>){if(busy)return;setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:String(e));setError(true)}finally{setBusy(false)}}
 const notify=(text:string)=>{setMessage(text);setError(false)};
 const geometry=()=>api('/counting').then(g=>{setLine(g.line);setZones(g.zones);notify('Regions saved. IN / OUT counters restart when geometry changes.')});
 const pick=(type:string)=>{uploadKind.current=type;if(fileRef.current){fileRef.current.accept=type==='image'?'.jpg,.jpeg,.png,.webp':'.mp4,.avi,.mov,.mkv,.webm';fileRef.current.click()}};
 const onFile=(file:File)=>run(async()=>{const type=uploadKind.current;setKind(type);setPage(type==='image'?'Image Upload':'Video Analysis');await api('/video/stop','POST');if(type==='image'){setImageFile(file);setStats(await upload('/detection/image',file))}else{const data=await upload('/video/upload',file);setVideoFile(data.file);setVideoUrl(data.url);setStats(await api('/video/start','POST',{file:data.file}))}});
 const start=()=>run(async()=>{if(kind==='image'){if(imageFile)setStats(await upload('/detection/image',imageFile));else pick('image')}else if(kind==='video'){if(videoFile)setStats(await api('/video/start','POST',{file:videoFile}));else pick('video')}else setStats(await api('/camera/start','POST',{index:camera}))});
 const navigate=(p:string)=>{setPage(p);if(p==='Live Detection')setKind('camera');if(p==='Image Upload')setKind('image');if(p==='Video Analysis')setKind('video')};
 const toggleOverlay=(key:string,value:boolean)=>run(async()=>{const body=Object.fromEntries(['boxes','track_ids','show_confidence','trajectories','centers'].map(k=>[k,k===key?value:settings[k]]));setSettings(await api('/overlays','PUT',body))});
 const names=showAllClasses?Object.values(models?.active?.classes||{}) as string[]:[];
 const dashboard=!['Settings','History','Analytics'].includes(page);
 const title=page==='Live Detection'?'Live detection':page==='Image Upload'?'Image analysis':page==='Video Analysis'?'Video analysis':page;
 return <div className="app"><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('Live Detection')}}><span className="brand-symbol"><Eye size={31}/></span><div>Vision<span>Counter</span><small>Detect <i>•</i> Track <i>•</i> Count</small></div></a><div className="top-metrics"><span className={'online '+(online?'':'offline')}><i/>{online?'System online':'Connecting…'}</span><span><Cpu size={14}/>{stats.cpu.toFixed(0)}% CPU</span><span><HardDrive size={14}/>{(stats.ram_gb?.toFixed(2)??'N/A')} GB</span><div className="top-divider"/><button title="Settings" onClick={()=>navigate('Settings')}><SettingsIcon size={18}/></button><button title="Toggle theme" onClick={()=>run(async()=>{const theme=settings?.theme==='light'?'dark':'light';setSettings(await api('/theme','PUT',{theme}))})}>{settings?.theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button className="avatar" title="Local workstation profile" onClick={()=>setProfile(!profile)}><User size={17}/></button></div></header>
 <aside className="sidebar"><div className="nav-label">WORKSPACE</div><nav>{pages.map(([p,Icon])=><button key={p} className={page===p?'nav-active':''} onClick={()=>navigate(p)}><Icon size={18}/><span>{p}</span>{page===p&&<ChevronRight size={14}/>}</button>)}</nav><div className="sidebar-bottom"><div className="local-badge"><Cpu size={16}/><b>Built for your CPU</b></div><p>Local processing.<br/>Real-time insights.<br/>Your data stays with you.</p><div className="grid-art"><Box size={68} strokeWidth={.65}/><Box size={32} strokeWidth={.7}/></div><a href="/docs" target="_blank" rel="noreferrer">API documentation <ExternalLink size={13}/></a></div><div className="version"><span className="tiny-dot"/>VisionCounter v1.0</div></aside>
 <main><div className="page-heading"><div><div className="breadcrumb">Workspace <ChevronRight size={12}/> {title}</div><h1>{title}<span className="pill">{stats.source_kind==='image'?'IMAGE':stats.status==='running'?'LIVE WORKSPACE':'VISION ANALYTICS'}</span></h1><p>{page==='Settings'?'Tune your model and performance for the way you work.':page==='History'?'Review saved sessions and export their detection metadata.':'Understand your scene. Track what matters. Count with confidence.'}</p></div><div className="row gap">{dashboard&&<button onClick={()=>pick(kind==='image'?'image':'video')}><Upload size={15}/>Upload {kind==='image'?'image':'video'}</button>}{stats.session_id&&<button onClick={()=>download(`/api/export/${stats.session_id}.csv`)}><Download size={15}/>Export CSV</button>}</div></div>
 {message&&<div className={'notice '+(error?'notice-error':'')} role="alert">{error?<AlertCircle size={17}/>:<CheckCircle2 size={17}/>}<span>{message}</span><button aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {stats.error&&<div className="notice notice-error"><AlertCircle size={17}/>{stats.error}</div>}
 {busy&&<div className="busy-bar" role="status"><span className="spinner"/>Working… Detection and model setup can take a moment on CPU.</div>}
 {!models?.active?.loaded&&page!=='Settings'&&<div className="setup-banner"><div><strong>Ready when you are.</strong><span>Install the lightweight pretrained model, or load your own in Settings.</span></div><button disabled={busy} className="primary" onClick={()=>run(async()=>{await api('/models/pretrained','POST');await refresh();notify('YOLO11 nano loaded. Choose an image, video, or camera to begin.')})}><Download size={15}/>Set up YOLO nano</button></div>}
 {dashboard&&<><div className="dashboard-grid"><div className="main-column"><VideoViewer stats={stats} busy={busy} kind={kind} camera={camera} setCamera={setCamera} onStart={start} onUpload={pick} run={run} videoUrl={videoUrl} line={line} zones={zones} onGeometry={geometry}/>
 <div className="overlay-bar"><span>OVERLAYS</span>{[['boxes','Boxes'],['track_ids','Track IDs'],['show_confidence','Confidence'],['trajectories','Trails'],['centers','Centers']].map(([key,label])=><label key={key}><input type="checkbox" checked={!!settings?.[key]} disabled={!settings||busy} onChange={e=>toggleOverlay(key,e.target.checked)}/>{label}</label>)}</div>
 {(mode==='Line crossing'||mode==='IN / OUT'||page==='Counting Modes')&&<div className="flow-cards"><div className="card"><ArrowDownLeft/><span>Entered</span><b>{stats.entered}</b></div><div className="card"><ArrowUpRight/><span>Exited</span><b>{stats.exited}</b></div><div className="card"><Layers/><span>Estimated inside</span><b>{stats.currently_inside}</b></div></div>}
 {(mode==='Zone counting'||page==='Counting Modes')&&<section className="card padded"><div className="card-title">Zone occupancy</div>{zones.length?<div className="zone-cards">{zones.map(z=><div key={z.name}><span>{z.name}</span><b>{stats.zones[z.name]||0}</b></div>)}</div>:<p className="muted small">Use “Add zone” under the viewer and draw at least three vertices.</p>}</section>}
 <AnalyticsCharts stats={stats}/><section className="card export-bar"><div><b>Keep your insights</b><small>Session metadata and annotated media, ready to share.</small></div><div className="row wrap gap"><button disabled={!stats.session_id} onClick={()=>download(`/api/export/${stats.session_id}.json`)}>JSON</button><button disabled={!stats.session_id} onClick={()=>download(`/api/export/${stats.session_id}.csv`)}>CSV</button>{kind==='image'&&stats.image_url&&<button onClick={()=>download(stats.image_url!)}><Download size={14}/>Result image</button>}{kind==='video'&&<button disabled={!videoFile||busy||job.status==='running'} onClick={()=>run(async()=>{await api('/video/stop','POST');setJob(await api('/video/export','POST',{file:videoFile}))})}><Download size={14}/>Export full video</button>}</div></section>
 {job.status!=='idle'&&<div className="notice">{job.status==='running'?`Rendering annotated video: ${job.progress}% (analysis is stopped during export)`:job.status==='error'?job.error:<><CheckCircle2 size={16}/>Annotated video ready. <button onClick={()=>download('/api/files/'+job.file)}>Download AVI</button><button onClick={()=>download(`/api/export/${job.session_id}.json`)}>Export metadata</button></>}</div>}
 </div><aside className="right-column"><ObjectCountPanel stats={stats} mode={mode} names={names}/><label className="class-toggle"><input type="checkbox" checked={showAllClasses} onChange={e=>setShowAllClasses(e.target.checked)}/>Show every model class</label><StatsPanel stats={stats}/><section className="card"><div className="card-title">Counting mode</div><div className="mode-grid">{modes.map(m=><button key={m} className={mode===m?'selected':''} onClick={()=>setMode(m)}>{m}</button>)}</div><p className="panel-foot">{mode==='IN / OUT'?'Inside = initial occupancy + entered − exited (floor 0).':'All counting metrics run together; choose what to inspect.'}</p></section><RecentDetections stats={stats}/></aside></div><div className="session-note"><Activity size={14}/>Unique counts represent tracker IDs. Re-entry, missed detections and ID switches can affect physical-object totals.</div></>}
 {page==='Analytics'&&<><div className="metric-grid">{[['Unique tracks',stats.total_unique],['Present now',stats.current_total],['Entered',stats.entered],['Exited',stats.exited]].map(([label,value])=><section key={label} className="card metric"><span>{label}</span><strong>{value}</strong></section>)}</div><AnalyticsCharts stats={stats}/><div className="analytics-bottom"><RecentDetections stats={stats}/><StatsPanel stats={stats}/></div></>}
 {page==='History'&&<section className="card padded"><div className="card-title">Recent sessions <button onClick={()=>run(async()=>setSessions(await api('/history')))}>Refresh</button></div><div className="table-scroll"><table className="history-table"><thead><tr><th>Started</th><th>Session / source</th><th>Status</th><th>Unique tracks</th><th>Export</th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td>{new Date(s.started*1000).toLocaleString()}</td><td><b>{s.id.slice(0,10)}</b><small>{s.source}</small></td><td>{s.ended?'Saved':'Active / interrupted'}</td><td>{s.summary?.total_unique??'—'}</td><td><div className="row gap"><button onClick={()=>download(`/api/export/${s.id}.csv`)}>CSV</button><button onClick={()=>download(`/api/export/${s.id}.json`)}>JSON</button></div></td></tr>)}</tbody></table>{!sessions.length&&<div className="large-empty"><History size={35}/><h3>Your session history starts here</h3><p>Analyze your first image, video or live camera.</p></div>}</div></section>}
 {page==='Settings'&&<Settings settings={settings} onSaved={s=>{setSettings(s);notify('Settings saved.')}} run={run} busy={busy} models={models} refresh={refresh}/>}
 <footer><span><i className="tiny-dot"/>{stats.status} <i>│</i> {stats.model||'No model loaded'} <i>│</i> {stats.image_size}px</span><span>Local vision. Clear insight.</span></footer></main>
 <input ref={fileRef} hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f);e.target.value=''}}/>
 {profile&&<div className="modal-backdrop" onClick={()=>setProfile(false)}><section className="card profile" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close profile" onClick={()=>setProfile(false)}><X size={18}/></button><div className="profile-icon"><User size={30}/></div><h2>Local workstation</h2><p>Single-user analysis on this computer.</p><p className="muted small">Media and analytics stay in the project folders. No account or cloud upload is required.</p><a href="/docs" target="_blank" rel="noreferrer">Explore API documentation ↗</a></section></div>}
 </div>
}
